"""Generate public AML validation example files.

The files generated by this script are intentionally checked into the repository.
They are user-facing fixtures for the editor and also the source of truth for SDK
validation tests.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from automationml import (
    Attribute,
    AttributeType,
    AttributeTypeLib,
    CAEXFile,
    InstanceHierarchy,
    InterfaceClass,
    InterfaceClassLib,
    InterfaceFamily,
    InternalElement,
    InternalLink,
    RoleClassLib,
    RoleFamily,
    RoleRequirements,
    SourceDocumentInformation,
    SupportedRoleClass,
    SystemUnitClassLib,
    SystemUnitFamily,
)

ROOT = Path(__file__).parents[1]
SUITE = ROOT / "examples" / "validation-suite"
JSON_DIR = SUITE / "json"
XML_DIR = SUITE / "xml"
FIXED_DATE = datetime(2026, 7, 3, tzinfo=timezone.utc)


@dataclass(frozen=True)
class ExampleCase:
    name: str
    size: str
    polarity: str
    title: str
    description: str
    document: CAEXFile


def source_document() -> SourceDocumentInformation:
    return SourceDocumentInformation(
        origin_name="AutomationML SDK validation suite",
        origin_id="automationml-validation-suite",
        origin_version="0.1.0",
        last_writing_date_time=FIXED_DATE,
    )


def caex_file(file_name: str, **kwargs) -> CAEXFile:
    return CAEXFile(
        file_name=file_name,
        superior_standard_versions=["AutomationML 2.1"],
        source_document_information=[source_document()],
        **kwargs,
    )


def attr(
    name: str,
    value: str,
    *,
    id: str | None = None,
    data_type: str = "xs:string",
    unit: str | None = None,
    ref_type: str | None = None,
) -> Attribute:
    return Attribute(
        id=id,
        name=name,
        value=value,
        attribute_data_type=data_type,
        unit=unit,
        ref_attribute_type=ref_type,
    )


def role_req(path: str) -> RoleRequirements:
    return RoleRequirements(ref_base_role_class_path=path)


def ext_if(
    name: str,
    id: str,
    ref: str,
) -> InterfaceClass:
    return InterfaceClass(id=id, name=name, ref_base_class_path=ref)


def attr_types_lib() -> AttributeTypeLib:
    return AttributeTypeLib(
        name="LineAttributeTypes",
        attribute_types=[
            AttributeType(
                name="CycleTime",
                attribute_data_type="xs:double",
                unit="s",
            ),
            AttributeType(
                name="PayloadKg",
                attribute_data_type="xs:double",
                unit="kg",
            ),
            AttributeType(name="Mode", attribute_data_type="xs:string"),
            AttributeType(
                name="Temperature",
                attribute_data_type="xs:double",
                unit="degC",
            ),
            AttributeType(name="QualityState", attribute_data_type="xs:string"),
        ],
    )


def interface_lib() -> InterfaceClassLib:
    return InterfaceClassLib(
        name="AutomationMLInterfaceClassLib",
        interface_classes=[
            InterfaceFamily(name="Port"),
            InterfaceFamily(
                name="PowerPort",
                ref_base_class_path="AutomationMLInterfaceClassLib/Port",
            ),
            InterfaceFamily(
                name="DataPort",
                ref_base_class_path="AutomationMLInterfaceClassLib/Port",
            ),
            InterfaceFamily(
                name="MaterialPort",
                ref_base_class_path="AutomationMLInterfaceClassLib/Port",
            ),
            InterfaceFamily(
                name="SafetyPort",
                ref_base_class_path="AutomationMLInterfaceClassLib/Port",
            ),
        ],
    )


def role_lib() -> RoleClassLib:
    return RoleClassLib(
        name="RoleClassLib",
        role_classes=[
            RoleFamily(name="Equipment"),
            RoleFamily(
                name="Robot",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
            RoleFamily(
                name="Conveyor",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
            RoleFamily(
                name="Buffer",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
            RoleFamily(
                name="QualityGate",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
            RoleFamily(
                name="Palletizer",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
            RoleFamily(
                name="SafetyDevice",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
        ],
    )


def system_unit_lib() -> SystemUnitClassLib:
    return SystemUnitClassLib(
        name="SystemUnitClassLib",
        system_unit_classes=[
            SystemUnitFamily(
                name="Cell",
                attributes=[
                    attr(
                        "cycleTime",
                        "42",
                        data_type="xs:double",
                        unit="s",
                        ref_type="LineAttributeTypes/CycleTime",
                    )
                ],
            ),
            SystemUnitFamily(
                name="RobotModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                attributes=[
                    attr(
                        "payload",
                        "12",
                        data_type="xs:double",
                        unit="kg",
                        ref_type="LineAttributeTypes/PayloadKg",
                    )
                ],
                external_interfaces=[
                    ext_if("Power", "robot-class-power", "AutomationMLInterfaceClassLib/PowerPort"),
                    ext_if("Data", "robot-class-data", "AutomationMLInterfaceClassLib/DataPort"),
                    ext_if("MaterialIn", "robot-class-mat-in", "AutomationMLInterfaceClassLib/MaterialPort"),
                    ext_if("MaterialOut", "robot-class-mat-out", "AutomationMLInterfaceClassLib/MaterialPort"),
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/Robot")
                ],
            ),
            SystemUnitFamily(
                name="ConveyorModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                external_interfaces=[
                    ext_if("MaterialIn", "conv-class-mat-in", "AutomationMLInterfaceClassLib/MaterialPort"),
                    ext_if("MaterialOut", "conv-class-mat-out", "AutomationMLInterfaceClassLib/MaterialPort"),
                    ext_if("Data", "conv-class-data", "AutomationMLInterfaceClassLib/DataPort"),
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/Conveyor")
                ],
            ),
            SystemUnitFamily(
                name="BufferModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                external_interfaces=[
                    ext_if("MaterialIn", "buffer-class-mat-in", "AutomationMLInterfaceClassLib/MaterialPort"),
                    ext_if("MaterialOut", "buffer-class-mat-out", "AutomationMLInterfaceClassLib/MaterialPort"),
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/Buffer")
                ],
            ),
            SystemUnitFamily(
                name="QualityGateModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                external_interfaces=[
                    ext_if("MaterialIn", "quality-class-mat-in", "AutomationMLInterfaceClassLib/MaterialPort"),
                    ext_if("MaterialOut", "quality-class-mat-out", "AutomationMLInterfaceClassLib/MaterialPort"),
                    ext_if("Data", "quality-class-data", "AutomationMLInterfaceClassLib/DataPort"),
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/QualityGate")
                ],
            ),
            SystemUnitFamily(
                name="PalletizerModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                external_interfaces=[
                    ext_if("MaterialIn", "pallet-class-mat-in", "AutomationMLInterfaceClassLib/MaterialPort"),
                    ext_if("Safety", "pallet-class-safety", "AutomationMLInterfaceClassLib/SafetyPort"),
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/Palletizer")
                ],
            ),
            SystemUnitFamily(
                name="SafetyScannerModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                external_interfaces=[
                    ext_if("Safety", "scanner-class-safety", "AutomationMLInterfaceClassLib/SafetyPort"),
                    ext_if("Data", "scanner-class-data", "AutomationMLInterfaceClassLib/DataPort"),
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/SafetyDevice")
                ],
            ),
        ],
    )


def medium_robot_cell_attribute_type_lib() -> AttributeTypeLib:
    return AttributeTypeLib(
        name="LineAttributeTypes",
        attribute_types=[
            AttributeType(name="AssetTag", attribute_data_type="xs:string"),
            AttributeType(
                name="CycleTime",
                attribute_data_type="xs:double",
                unit="s",
            ),
            AttributeType(
                name="PayloadKg",
                attribute_data_type="xs:double",
                unit="kg",
            ),
            AttributeType(name="QualityState", attribute_data_type="xs:string"),
        ],
    )


def medium_robot_cell_interface_lib() -> InterfaceClassLib:
    return InterfaceClassLib(
        name="AutomationMLInterfaceClassLib",
        interface_classes=[
            InterfaceFamily(name="Port"),
            InterfaceFamily(
                name="DataPort",
                ref_base_class_path="AutomationMLInterfaceClassLib/Port",
            ),
            InterfaceFamily(
                name="MaterialPort",
                ref_base_class_path="AutomationMLInterfaceClassLib/Port",
            ),
        ],
    )


def medium_robot_cell_role_lib() -> RoleClassLib:
    return RoleClassLib(
        name="RoleClassLib",
        role_classes=[
            RoleFamily(name="Equipment"),
            RoleFamily(
                name="Conveyor",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
            RoleFamily(
                name="Robot",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
            RoleFamily(
                name="QualityGate",
                ref_base_class_path="RoleClassLib/Equipment",
            ),
        ],
    )


def medium_robot_cell_system_unit_lib() -> SystemUnitClassLib:
    return SystemUnitClassLib(
        name="SystemUnitClassLib",
        system_unit_classes=[
            SystemUnitFamily(
                name="Asset",
                attributes=[
                    attr(
                        "assetTag",
                        "asset",
                        ref_type="LineAttributeTypes/AssetTag",
                    )
                ],
            ),
            SystemUnitFamily(
                name="Cell",
                ref_base_class_path="SystemUnitClassLib/Asset",
                attributes=[
                    attr(
                        "cycleTime",
                        "42",
                        data_type="xs:double",
                        unit="s",
                        ref_type="LineAttributeTypes/CycleTime",
                    )
                ],
                external_interfaces=[
                    ext_if(
                        "Data",
                        "cell-class-data",
                        "AutomationMLInterfaceClassLib/DataPort",
                    )
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/Equipment")
                ],
            ),
            SystemUnitFamily(
                name="ConveyorModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                external_interfaces=[
                    ext_if(
                        "MaterialOut",
                        "conveyor-class-material-out",
                        "AutomationMLInterfaceClassLib/MaterialPort",
                    )
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/Conveyor")
                ],
            ),
            SystemUnitFamily(
                name="RobotModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                attributes=[
                    attr(
                        "payload",
                        "12",
                        data_type="xs:double",
                        unit="kg",
                        ref_type="LineAttributeTypes/PayloadKg",
                    )
                ],
                external_interfaces=[
                    ext_if(
                        "MaterialIn",
                        "robot-class-material-in",
                        "AutomationMLInterfaceClassLib/MaterialPort",
                    )
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/Robot")
                ],
            ),
            SystemUnitFamily(
                name="QualityGateModule",
                ref_base_class_path="SystemUnitClassLib/Cell",
                attributes=[
                    attr(
                        "qualityState",
                        "ready",
                        ref_type="LineAttributeTypes/QualityState",
                    )
                ],
                supported_role_classes=[
                    SupportedRoleClass(ref_role_class_path="RoleClassLib/QualityGate")
                ],
            ),
        ],
    )


def small_valid() -> CAEXFile:
    return caex_file(
        "small-valid-motor.aml",
        attribute_type_libs=[
            AttributeTypeLib(
                name="ExampleAttributeTypeLib",
                attribute_types=[
                    AttributeType(
                        name="Speed",
                        attribute_data_type="xs:double",
                        unit="rpm",
                    )
                ],
            )
        ],
        role_class_libs=[
            RoleClassLib(
                name="ExampleRoleClassLib",
                role_classes=[RoleFamily(name="Drive")],
            )
        ],
        interface_class_libs=[
            InterfaceClassLib(
                name="ExampleInterfaceClassLib",
                interface_classes=[
                    InterfaceFamily(name="Port"),
                    InterfaceFamily(
                        name="PowerPort",
                        ref_base_class_path="ExampleInterfaceClassLib/Port",
                    ),
                ],
            )
        ],
        system_unit_class_libs=[
            SystemUnitClassLib(
                name="ExampleSystemUnitClassLib",
                system_unit_classes=[
                    SystemUnitFamily(
                        name="Motor",
                        attributes=[
                            attr(
                                "speed",
                                "1500",
                                data_type="xs:double",
                                unit="rpm",
                                ref_type="ExampleAttributeTypeLib/Speed",
                            )
                        ],
                        external_interfaces=[
                            ext_if(
                                "Power",
                                "motor-class-power",
                                "ExampleInterfaceClassLib/PowerPort",
                            )
                        ],
                        supported_role_classes=[
                            SupportedRoleClass(
                                ref_role_class_path="ExampleRoleClassLib/Drive"
                            )
                        ],
                    )
                ],
            )
        ],
        instance_hierarchies=[
            InstanceHierarchy(
                name="Plant",
                internal_elements=[
                    InternalElement(
                        id="ie-motor-1",
                        name="Motor-1",
                        ref_base_system_unit_path="ExampleSystemUnitClassLib/Motor",
                        attributes=[
                            attr(
                                "speed",
                                "1500",
                                data_type="xs:double",
                                unit="rpm",
                                ref_type="ExampleAttributeTypeLib/Speed",
                            )
                        ],
                        external_interfaces=[
                            ext_if(
                                "Power",
                                "if-motor-power",
                                "ExampleInterfaceClassLib/PowerPort",
                            )
                        ],
                        role_requirements=[
                            role_req("ExampleRoleClassLib/Drive")
                        ],
                    )
                ],
            )
        ],
    )


def small_invalid() -> CAEXFile:
    return caex_file(
        "small-invalid-unresolved-references.aml",
        instance_hierarchies=[
            InstanceHierarchy(
                name="Plant",
                internal_elements=[
                    InternalElement(
                        id="ie-motor-1",
                        name="Motor-1",
                        ref_base_system_unit_path="MissingSystemUnits/Motor",
                        attributes=[
                            attr(
                                "speed",
                                "1500",
                                data_type="xs:double",
                                unit="rpm",
                                ref_type="MissingAttributeTypes/Speed",
                            )
                        ],
                        external_interfaces=[
                            ext_if(
                                "Power",
                                "if-motor-power",
                                "MissingInterfaces/PowerPort",
                            )
                        ],
                        role_requirements=[
                            role_req("MissingRoles/Drive")
                        ],
                    )
                ],
            )
        ],
    )


def small_robot_cell_warning_missing_inherited_attribute() -> CAEXFile:
    return caex_file(
        "small_robot-cell_warning_missing-inherited-attribute.aml",
        attribute_type_libs=[
            AttributeTypeLib(
                name="LineAttributeTypes",
                attribute_types=[
                    AttributeType(
                        name="CycleTime",
                        attribute_data_type="xs:double",
                        unit="s",
                    ),
                    AttributeType(
                        name="PayloadKg",
                        attribute_data_type="xs:double",
                        unit="kg",
                    ),
                ],
            )
        ],
        role_class_libs=[
            RoleClassLib(
                name="RoleClassLib",
                role_classes=[
                    RoleFamily(name="Equipment"),
                    RoleFamily(
                        name="Robot",
                        ref_base_class_path="RoleClassLib/Equipment",
                    ),
                ],
            )
        ],
        system_unit_class_libs=[
            SystemUnitClassLib(
                name="SystemUnitClassLib",
                system_unit_classes=[
                    SystemUnitFamily(
                        name="Cell",
                        attributes=[
                            attr(
                                "cycleTime",
                                "42",
                                data_type="xs:double",
                                unit="s",
                                ref_type="LineAttributeTypes/CycleTime",
                            )
                        ],
                    ),
                    SystemUnitFamily(
                        name="RobotModule",
                        ref_base_class_path="SystemUnitClassLib/Cell",
                        attributes=[
                            attr(
                                "payload",
                                "12",
                                data_type="xs:double",
                                unit="kg",
                                ref_type="LineAttributeTypes/PayloadKg",
                            )
                        ],
                        supported_role_classes=[
                            SupportedRoleClass(
                                ref_role_class_path="RoleClassLib/Robot"
                            )
                        ],
                    ),
                ],
            )
        ],
        instance_hierarchies=[
            InstanceHierarchy(
                name="RobotCell",
                internal_elements=[
                    InternalElement(
                        id="small-robot-cell-1",
                        name="RobotCell-1",
                        ref_base_system_unit_path="SystemUnitClassLib/Cell",
                        attributes=[
                            attr(
                                "cycleTime",
                                "38",
                                data_type="xs:double",
                                unit="s",
                                ref_type="LineAttributeTypes/CycleTime",
                            )
                        ],
                        role_requirements=[
                            role_req("RoleClassLib/Equipment")
                        ],
                        internal_elements=[
                            InternalElement(
                                id="small-robot-arm-1",
                                name="RobotArm",
                                ref_base_system_unit_path="SystemUnitClassLib/RobotModule",
                                attributes=[
                                    attr(
                                        "payload",
                                        "10",
                                        data_type="xs:double",
                                        unit="kg",
                                        ref_type="LineAttributeTypes/PayloadKg",
                                    )
                                ],
                                role_requirements=[role_req("RoleClassLib/Robot")],
                            )
                        ],
                    )
                ],
            )
        ],
    )


def medium_valid() -> CAEXFile:
    return caex_file(
        "medium-valid-robot-cell.aml",
        attribute_type_libs=[medium_robot_cell_attribute_type_lib()],
        interface_class_libs=[medium_robot_cell_interface_lib()],
        role_class_libs=[medium_robot_cell_role_lib()],
        system_unit_class_libs=[medium_robot_cell_system_unit_lib()],
        instance_hierarchies=[
            InstanceHierarchy(
                name="PackagingCell",
                internal_elements=[
                    InternalElement(
                        id="cell-1",
                        name="RobotCell-1",
                        ref_base_system_unit_path="SystemUnitClassLib/Cell",
                        attributes=[
                            attr(
                                "assetTag",
                                "CELL-1",
                                ref_type="LineAttributeTypes/AssetTag",
                            ),
                            attr(
                                "cycleTime",
                                "38",
                                data_type="xs:double",
                                unit="s",
                                ref_type="LineAttributeTypes/CycleTime",
                            )
                        ],
                        external_interfaces=[
                            ext_if(
                                "Data",
                                "cell-1-data",
                                "AutomationMLInterfaceClassLib/DataPort",
                            )
                        ],
                        internal_elements=[
                            InternalElement(
                                id="cell-1-conveyor",
                                name="InfeedConveyor",
                                ref_base_system_unit_path="SystemUnitClassLib/ConveyorModule",
                                attributes=[
                                    attr(
                                        "assetTag",
                                        "CONV-1",
                                        ref_type="LineAttributeTypes/AssetTag",
                                    ),
                                    attr(
                                        "cycleTime",
                                        "8",
                                        data_type="xs:double",
                                        unit="s",
                                        ref_type="LineAttributeTypes/CycleTime",
                                    ),
                                ],
                                external_interfaces=[
                                    ext_if(
                                        "MaterialOut",
                                        "cell-1-conveyor-out",
                                        "AutomationMLInterfaceClassLib/MaterialPort",
                                    ),
                                    ext_if(
                                        "Data",
                                        "cell-1-conveyor-data",
                                        "AutomationMLInterfaceClassLib/DataPort",
                                    ),
                                ],
                                role_requirements=[
                                    role_req("RoleClassLib/Conveyor")
                                ],
                            ),
                            InternalElement(
                                id="cell-1-robot",
                                name="RobotArm",
                                ref_base_system_unit_path="SystemUnitClassLib/RobotModule",
                                attributes=[
                                    attr(
                                        "assetTag",
                                        "ROBOT-1",
                                        ref_type="LineAttributeTypes/AssetTag",
                                    ),
                                    attr(
                                        "cycleTime",
                                        "12",
                                        data_type="xs:double",
                                        unit="s",
                                        ref_type="LineAttributeTypes/CycleTime",
                                    ),
                                    attr(
                                        "payload",
                                        "10",
                                        data_type="xs:double",
                                        unit="kg",
                                        ref_type="LineAttributeTypes/PayloadKg",
                                    )
                                ],
                                external_interfaces=[
                                    ext_if(
                                        "MaterialIn",
                                        "cell-1-robot-in",
                                        "AutomationMLInterfaceClassLib/MaterialPort",
                                    ),
                                    ext_if(
                                        "Data",
                                        "cell-1-robot-data",
                                        "AutomationMLInterfaceClassLib/DataPort",
                                    ),
                                ],
                                role_requirements=[role_req("RoleClassLib/Robot")],
                            ),
                            InternalElement(
                                id="cell-1-quality",
                                name="VisionGate",
                                ref_base_system_unit_path="SystemUnitClassLib/QualityGateModule",
                                attributes=[
                                    attr(
                                        "assetTag",
                                        "QUALITY-1",
                                        ref_type="LineAttributeTypes/AssetTag",
                                    ),
                                    attr(
                                        "cycleTime",
                                        "6",
                                        data_type="xs:double",
                                        unit="s",
                                        ref_type="LineAttributeTypes/CycleTime",
                                    ),
                                    attr(
                                        "qualityState",
                                        "ready",
                                        ref_type="LineAttributeTypes/QualityState",
                                    ),
                                ],
                                external_interfaces=[
                                    ext_if(
                                        "Data",
                                        "cell-1-quality-data",
                                        "AutomationMLInterfaceClassLib/DataPort",
                                    ),
                                ],
                                role_requirements=[
                                    role_req("RoleClassLib/QualityGate")
                                ],
                            ),
                        ],
                        internal_links=[
                            InternalLink(
                                name="MaterialToRobot",
                                ref_partner_side_a="cell-1-conveyor-out",
                                ref_partner_side_b="cell-1-robot-in",
                            ),
                            InternalLink(
                                name="QualityFeedback",
                                ref_partner_side_a="cell-1-data",
                                ref_partner_side_b="cell-1-quality-data",
                            ),
                        ],
                    )
                ],
            )
        ],
    )


def medium_robot_cell_warning_missing_inherited_attribute_and_class_interface() -> CAEXFile:
    return caex_file(
        "medium_robot-cell_warning_missing-inherited-attribute-and-class-interface.aml",
        attribute_type_libs=[
            AttributeTypeLib(
                name="LineAttributeTypes",
                attribute_types=[
                    AttributeType(
                        name="CycleTime",
                        attribute_data_type="xs:double",
                        unit="s",
                    ),
                    AttributeType(
                        name="PayloadKg",
                        attribute_data_type="xs:double",
                        unit="kg",
                    ),
                ],
            )
        ],
        interface_class_libs=[
            InterfaceClassLib(
                name="AutomationMLInterfaceClassLib",
                interface_classes=[
                    InterfaceFamily(name="Port"),
                    InterfaceFamily(
                        name="PowerPort",
                        ref_base_class_path="AutomationMLInterfaceClassLib/Port",
                    ),
                    InterfaceFamily(
                        name="DataPort",
                        ref_base_class_path="AutomationMLInterfaceClassLib/Port",
                    ),
                    InterfaceFamily(
                        name="MaterialPort",
                        ref_base_class_path="AutomationMLInterfaceClassLib/Port",
                    ),
                ],
            )
        ],
        role_class_libs=[
            RoleClassLib(
                name="RoleClassLib",
                role_classes=[
                    RoleFamily(name="Equipment"),
                    RoleFamily(
                        name="Robot",
                        ref_base_class_path="RoleClassLib/Equipment",
                    ),
                    RoleFamily(
                        name="QualityGate",
                        ref_base_class_path="RoleClassLib/Equipment",
                    ),
                ],
            )
        ],
        system_unit_class_libs=[
            SystemUnitClassLib(
                name="SystemUnitClassLib",
                system_unit_classes=[
                    SystemUnitFamily(
                        name="Cell",
                        attributes=[
                            attr(
                                "cycleTime",
                                "42",
                                data_type="xs:double",
                                unit="s",
                                ref_type="LineAttributeTypes/CycleTime",
                            )
                        ],
                    ),
                    SystemUnitFamily(
                        name="RobotModule",
                        ref_base_class_path="SystemUnitClassLib/Cell",
                        attributes=[
                            attr(
                                "payload",
                                "12",
                                data_type="xs:double",
                                unit="kg",
                                ref_type="LineAttributeTypes/PayloadKg",
                            )
                        ],
                        external_interfaces=[
                            ext_if(
                                "Power",
                                "robot-class-power",
                                "AutomationMLInterfaceClassLib/PowerPort",
                            ),
                            ext_if(
                                "Data",
                                "robot-class-data",
                                "AutomationMLInterfaceClassLib/DataPort",
                            ),
                            ext_if(
                                "MaterialIn",
                                "robot-class-material-in",
                                "AutomationMLInterfaceClassLib/MaterialPort",
                            ),
                            ext_if(
                                "MaterialOut",
                                "robot-class-material-out",
                                "AutomationMLInterfaceClassLib/MaterialPort",
                            ),
                        ],
                        supported_role_classes=[
                            SupportedRoleClass(
                                ref_role_class_path="RoleClassLib/Robot"
                            )
                        ],
                    ),
                    SystemUnitFamily(
                        name="QualityGateModule",
                        ref_base_class_path="SystemUnitClassLib/Cell",
                        external_interfaces=[
                            ext_if(
                                "MaterialIn",
                                "quality-class-material-in",
                                "AutomationMLInterfaceClassLib/MaterialPort",
                            ),
                            ext_if(
                                "MaterialOut",
                                "quality-class-material-out",
                                "AutomationMLInterfaceClassLib/MaterialPort",
                            ),
                            ext_if(
                                "Data",
                                "quality-class-data",
                                "AutomationMLInterfaceClassLib/DataPort",
                            ),
                        ],
                        supported_role_classes=[
                            SupportedRoleClass(
                                ref_role_class_path="RoleClassLib/QualityGate"
                            )
                        ],
                    ),
                ],
            )
        ],
        instance_hierarchies=[
            InstanceHierarchy(
                name="RobotCell",
                internal_elements=[
                    InternalElement(
                        id="medium-robot-cell-1",
                        name="RobotCell-1",
                        ref_base_system_unit_path="SystemUnitClassLib/Cell",
                        attributes=[
                            attr(
                                "cycleTime",
                                "38",
                                data_type="xs:double",
                                unit="s",
                                ref_type="LineAttributeTypes/CycleTime",
                            )
                        ],
                        external_interfaces=[
                            ext_if(
                                "Data",
                                "medium-cell-data",
                                "AutomationMLInterfaceClassLib/DataPort",
                            )
                        ],
                        internal_elements=[
                            InternalElement(
                                id="medium-cell-robot",
                                name="RobotArm",
                                ref_base_system_unit_path="SystemUnitClassLib/RobotModule",
                                attributes=[
                                    attr(
                                        "payload",
                                        "10",
                                        data_type="xs:double",
                                        unit="kg",
                                        ref_type="LineAttributeTypes/PayloadKg",
                                    )
                                ],
                                external_interfaces=[
                                    ext_if(
                                        "MaterialIn",
                                        "medium-robot-material-in",
                                        "AutomationMLInterfaceClassLib/MaterialPort",
                                    ),
                                    ext_if(
                                        "Data",
                                        "medium-robot-data",
                                        "AutomationMLInterfaceClassLib/DataPort",
                                    ),
                                ],
                                role_requirements=[
                                    role_req("RoleClassLib/Robot")
                                ],
                            ),
                            InternalElement(
                                id="medium-cell-quality",
                                name="VisionGate",
                                ref_base_system_unit_path=(
                                    "SystemUnitClassLib/QualityGateModule"
                                ),
                                external_interfaces=[
                                    ext_if(
                                        "MaterialIn",
                                        "medium-quality-material-in",
                                        "AutomationMLInterfaceClassLib/MaterialPort",
                                    ),
                                    ext_if(
                                        "Data",
                                        "medium-quality-data",
                                        "AutomationMLInterfaceClassLib/DataPort",
                                    ),
                                ],
                                role_requirements=[
                                    role_req("RoleClassLib/QualityGate")
                                ],
                            ),
                        ],
                        internal_links=[
                            InternalLink(
                                name="VisionFeedback",
                                ref_partner_side_a="medium-cell-data",
                                ref_partner_side_b="medium-quality-data",
                            )
                        ],
                    )
                ],
            )
        ],
    )


def medium_invalid() -> CAEXFile:
    document = medium_valid().model_copy(deep=True)
    document.file_name = "medium-invalid-duplicates-and-links.aml"
    cell = document.instance_hierarchies[0].internal_elements[0]
    conveyor = cell.internal_elements[0]
    robot = cell.internal_elements[1]
    conveyor.external_interfaces[1].id = "cell-1-data"
    cell.internal_links[0].ref_partner_side_b = "missing-robot-interface"
    robot.role_requirements[0].ref_base_role_class_path = "RoleClassLib/MissingRobot"
    document.system_unit_class_libs[0].system_unit_classes.append(
        SystemUnitFamily(name="RobotModule")
    )
    return document


def big_valid() -> CAEXFile:
    cells: list[InternalElement] = []
    for cell_index in range(1, 4):
        prefix = f"line-a-cell-{cell_index}"
        cells.append(
            InternalElement(
                id=prefix,
                name=f"PackagingCell-{cell_index}",
                ref_base_system_unit_path="SystemUnitClassLib/Cell",
                attributes=[
                    attr(
                        "cycleTime",
                        str(35 + cell_index),
                        data_type="xs:double",
                        unit="s",
                        ref_type="LineAttributeTypes/CycleTime",
                    ),
                    attr(
                        "mode",
                        "automatic",
                        ref_type="LineAttributeTypes/Mode",
                    ),
                ],
                external_interfaces=[
                    ext_if("Data", f"{prefix}-data", "AutomationMLInterfaceClassLib/DataPort"),
                    ext_if("Safety", f"{prefix}-safety", "AutomationMLInterfaceClassLib/SafetyPort"),
                ],
                internal_elements=[
                    line_module(prefix, "InfeedConveyor", "ConveyorModule", "Conveyor", "conv"),
                    line_module(prefix, "RobotArm", "RobotModule", "Robot", "robot"),
                    line_module(prefix, "Buffer", "BufferModule", "Buffer", "buffer"),
                    line_module(prefix, "QualityGate", "QualityGateModule", "QualityGate", "quality"),
                    line_module(prefix, "Palletizer", "PalletizerModule", "Palletizer", "pallet"),
                    line_module(prefix, "SafetyScanner", "SafetyScannerModule", "SafetyDevice", "scanner"),
                ],
                internal_links=[
                    InternalLink(
                        name="ConveyorToRobot",
                        ref_partner_side_a=f"{prefix}-conv-material-out",
                        ref_partner_side_b=f"{prefix}-robot-material-in",
                    ),
                    InternalLink(
                        name="RobotToBuffer",
                        ref_partner_side_a=f"{prefix}-robot-material-out",
                        ref_partner_side_b=f"{prefix}-buffer-material-in",
                    ),
                    InternalLink(
                        name="BufferToQuality",
                        ref_partner_side_a=f"{prefix}-buffer-material-out",
                        ref_partner_side_b=f"{prefix}-quality-material-in",
                    ),
                    InternalLink(
                        name="QualityToPalletizer",
                        ref_partner_side_a=f"{prefix}-quality-material-out",
                        ref_partner_side_b=f"{prefix}-pallet-material-in",
                    ),
                    InternalLink(
                        name="CellSafety",
                        ref_partner_side_a=f"{prefix}-safety",
                        ref_partner_side_b=f"{prefix}-scanner-safety",
                    ),
                    InternalLink(
                        name="QualityData",
                        ref_partner_side_a=f"{prefix}-data",
                        ref_partner_side_b=f"{prefix}-quality-data",
                    ),
                ],
                role_requirements=[role_req("RoleClassLib/Equipment")],
            )
        )

    return caex_file(
        "big-valid-packaging-line.aml",
        attribute_type_libs=[attr_types_lib()],
        interface_class_libs=[interface_lib()],
        role_class_libs=[role_lib()],
        system_unit_class_libs=[system_unit_lib()],
        instance_hierarchies=[
            InstanceHierarchy(name="FactoryLine", internal_elements=cells)
        ],
    )


def line_module(
    prefix: str,
    name: str,
    system_unit: str,
    role: str,
    id_suffix: str,
) -> InternalElement:
    interfaces = [
        ext_if(
            "MaterialIn",
            f"{prefix}-{id_suffix}-material-in",
            "AutomationMLInterfaceClassLib/MaterialPort",
        ),
        ext_if(
            "MaterialOut",
            f"{prefix}-{id_suffix}-material-out",
            "AutomationMLInterfaceClassLib/MaterialPort",
        ),
        ext_if("Data", f"{prefix}-{id_suffix}-data", "AutomationMLInterfaceClassLib/DataPort"),
    ]
    if role == "SafetyDevice":
        interfaces.append(
            ext_if(
                "Safety",
                f"{prefix}-{id_suffix}-safety",
                "AutomationMLInterfaceClassLib/SafetyPort",
            )
        )
    return InternalElement(
        id=f"{prefix}-{id_suffix}",
        name=name,
        ref_base_system_unit_path=f"SystemUnitClassLib/{system_unit}",
        attributes=[
            attr(
                "mode",
                "automatic",
                ref_type="LineAttributeTypes/Mode",
            )
        ],
        external_interfaces=interfaces,
        role_requirements=[role_req(f"RoleClassLib/{role}")],
    )


def big_invalid() -> CAEXFile:
    document = big_valid().model_copy(deep=True)
    document.file_name = "big-invalid-mixed-references.aml"
    first_cell = document.instance_hierarchies[0].internal_elements[0]
    second_cell = document.instance_hierarchies[0].internal_elements[1]
    third_cell = document.instance_hierarchies[0].internal_elements[2]

    first_cell.ref_base_system_unit_path = "MissingSystemUnits/Cell"
    first_cell.attributes[0].ref_attribute_type = "MissingAttributeTypes/CycleTime"
    first_cell.internal_elements[0].external_interfaces[0].ref_base_class_path = (
        "MissingInterfaces/MaterialPort"
    )
    first_cell.internal_elements[1].role_requirements[0].ref_base_role_class_path = (
        "MissingRoles/Robot"
    )
    first_cell.internal_links[0].ref_partner_side_b = "missing-robot-material-in"
    second_cell.internal_elements[0].id = third_cell.internal_elements[0].id
    second_cell.internal_elements[2].role_requirements[0].ref_base_role_class_path = (
        "MissingRoles/Buffer"
    )
    return document


def cases() -> list[ExampleCase]:
    return [
        ExampleCase(
            name="small-valid-motor",
            size="small",
            polarity="positive",
            title="Small valid motor",
            description="A minimal motor instance with resolved system unit, role, and attribute type references.",
            document=small_valid(),
        ),
        ExampleCase(
            name="small-invalid-unresolved-references",
            size="small",
            polarity="negative",
            title="Small invalid unresolved references",
            description="A compact document with unresolved system unit, role, interface, and attribute type references.",
            document=small_invalid(),
        ),
        ExampleCase(
            name="small_robot-cell_warning_missing-inherited-attribute",
            size="small",
            polarity="warning",
            title="Small robot cell warning: missing inherited attribute",
            description="A compact valid robot cell where a RobotModule instance omits the inherited Cell cycleTime attribute.",
            document=small_robot_cell_warning_missing_inherited_attribute(),
        ),
        ExampleCase(
            name="medium-valid-robot-cell",
            size="medium",
            polarity="positive",
            title="Medium valid robot cell",
            description="A robot cell with class libraries, nested internal elements, role requirements, and internal links.",
            document=medium_valid(),
        ),
        ExampleCase(
            name="medium_robot-cell_warning_missing-inherited-attribute-and-class-interface",
            size="medium",
            polarity="warning",
            title="Medium robot cell warning: missing inherited attribute and class interface",
            description="A valid robot cell where instances omit inherited attributes and selected SystemUnitClass interfaces.",
            document=medium_robot_cell_warning_missing_inherited_attribute_and_class_interface(),
        ),
        ExampleCase(
            name="medium-invalid-duplicates-and-links",
            size="medium",
            polarity="negative",
            title="Medium invalid duplicates and links",
            description="A robot cell with duplicate IDs, duplicate class paths, a missing role, and a broken internal link.",
            document=medium_invalid(),
        ),
        ExampleCase(
            name="big-valid-packaging-line",
            size="big",
            polarity="positive",
            title="Big valid packaging line",
            description="A larger multi-cell packaging line for graph, tree, filtering, and roundtrip testing.",
            document=big_valid(),
        ),
        ExampleCase(
            name="big-invalid-mixed-references",
            size="big",
            polarity="negative",
            title="Big invalid mixed references",
            description="A larger line with mixed unresolved references, duplicate IDs, and a broken internal link.",
            document=big_invalid(),
        ),
    ]


def main() -> None:
    JSON_DIR.mkdir(parents=True, exist_ok=True)
    XML_DIR.mkdir(parents=True, exist_ok=True)
    manifest: list[dict[str, object]] = []

    for example in cases():
        document = example.document
        json_path = JSON_DIR / f"{example.name}.json"
        xml_path = XML_DIR / f"{example.name}.aml"
        json_path.write_text(document.to_aml_json(indent=2) + "\n", encoding="utf-8")
        xml_path.write_text(
            document.to_aml_xml(pretty=True, include_default_change_mode=True),
            encoding="utf-8",
        )
        issues = document.caex_validation_issues()
        code_counts = Counter(issue.code for issue in issues)
        severity_counts = Counter(issue.severity for issue in issues)
        manifest.append(
            {
                "name": example.name,
                "title": example.title,
                "size": example.size,
                "polarity": example.polarity,
                "description": example.description,
                "json": f"json/{json_path.name}",
                "xml": f"xml/{xml_path.name}",
                "expected_valid": severity_counts.get("error", 0) == 0,
                "expected_issue_count": len(issues),
                "expected_error_count": severity_counts.get("error", 0),
                "expected_warning_count": severity_counts.get("warning", 0),
                "expected_issue_counts": dict(sorted(code_counts.items())),
                "expected_severity_counts": dict(sorted(severity_counts.items())),
            }
        )

    (SUITE / "manifest.json").write_text(
        json.dumps({"cases": manifest}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
